pipeline {
    agent any

    options {
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {
        // Stage 1: Source Code Checkout
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/binod0506devops-pixel/jenkins-pipeline-ci-cd-v1.git'
            }
        }

        // Stage 2: Build
        stage('Build') {
            steps {
                dir('New folder') {
                    sh 'mvn clean package'
                }
            }
        }

        // Stage 3: Unit Testing
        stage('Unit Testing') {
            steps {
                dir('New folder') {
                    sh 'mvn test'
                }
            }
        }

        // Stage 4: Static Code Analysis (SonarQube)
        stage('Static Code Analysis') {
            steps {
                dir('New folder') {
                    withSonarQubeEnv('SonarScanner') {
                        sh 'mvn sonar:sonar \
                            -Dsonar.projectKey=jenkins-pipeline-project \
                            -Dsonar.projectName=jenkins-pipeline-project \
                            -Dsonar.host.url=http://51.21.190.32:9000'
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}