pipeline {
    agent any

    options {
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {
        // Stage 1: Source Code Checkout
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/binod0506devops-pixel/jenkins-pipeline-ci-cd-v1.git'
            }
        }

        // Stage 2: Build
        stage('Build') {
            steps {
                dir('New folder') {
                    sh 'mvn clean package'
                }
            }
        }

        // Stage 3: Unit Testing
        stage('Unit Testing') {
            steps {
                dir('New folder') {
                    sh 'mvn test'
                }
            }
        }

        // Stage 4: Static Code Analysis (SonarQube)
        stage('Static Code Analysis') {
            steps {
                dir('New folder') {
                    withSonarQubeEnv('SonarQube servers') {
                        sh '''
                            echo "SONAR_HOST_URL=$SONAR_HOST_URL"

                            mvn sonar:sonar \
                            -Dsonar.projectKey=jenkins-pipeline-project \
                            -Dsonar.projectName=jenkins-pipeline-project
                        '''
                    }

                }
            }
        }

        stage('Debug Sonar') {
            steps {
                withSonarQubeEnv('SonarQube servers') {
                    sh '''
                        env | grep SONAR
                    '''
                }
            }
        }
        stage('Verify Dockerfile') {
            steps {
                dir('New folder') {
                    sh '''
                        pwd
                        ls -ltr
                    '''
                }
            }
        }

        stage('Docker Image Build') {
            steps {
                dir('New folder') {
                    sh '''
                        echo "Building Docker Image..."

                        docker build \
                        -t binod0506devops/jenkins-pipeline-project:${BUILD_NUMBER} \
                        .
                    '''
                }
            }
        }


    }

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}